### ISSUE TITLE
Error 404 with some long payload

### ISSUE THREAD

**Issue by PixEye** [jihchi/mermaid.ink#166]
Do you know why this request fails in error 404 while GitHub & GitLab succeed to show it please?

https://mermaid.ink/img/eyJjb2RlIjoiICBmbG93Y2hhcnQgVERcbiAgICBSZWFkU2NyaXB0UGFyYW1ldGVycyhSZWFkIHNjcmlwdCBwYXJhbWV0ZXJzKSAtLT5cbiAgICBDaG9vc2VQb2RBbmRUZW5hbnQoQ2hvb3NlIFBPRCBhbmQgdGVuYW50XFxuIERlZmF1bHQgdmFsdWVzIGFyZSBpbiBjb25maWcpIC0tPlxuICAgIFBvZEFuZFRlbmFudEZvdW5ke3tQT0QgYW5kIHRlbmFudCBmb3VuZD99fVxuICAgIFBvZEFuZFRlbmFudEZvdW5kIC0tIE5vIC0tPiBTdG9wKFNUT1Agc3luY2hyb1xcbiB3aXRoIGZhaWx1cmUgc3RhdHVzKVxuICAgIFBvZEFuZFRlbmFudEZvdW5kIC0tIFllcyAtLT4gVXNlclNvdXJjZUNvbmZpZ3VyZWR7e0FueSB1c2VyIHNvdXJjZSBjb25maWd1cmVkP319XG5cbiAgICBVc2VyU291cmNlQ29uZmlndXJlZCAtLSBObyAtLT4gU3RvcFxuICAgIFVzZXJTb3VyY2VDb25maWd1cmVkIC0tIFllcyAtLT4gTWVtYmVyU291cmNlQ29uZmlndXJlZHt7QW55IG1lbWJlciBzb3VyY2UgY29uZmlndXJlZD99fVxuICAgIE1lbWJlclNvdXJjZUNvbmZpZ3VyZWQgLS0gWWVzIC0tPiBSZWFkTWVtYmVyU291cmNlcyhSZWFkIGFsbCBtZW1iZXIgc291cmNlcylcbiAgICBNZW1iZXJTb3VyY2VDb25maWd1cmVkIC0tIE5vICAtLT4gRXh0ZXJuYWxTb3VyY2VDb25maWd1cmVke3tBbnkgZXh0ZXJuYWwgc291cmNlIGNvbmZpZ3VyZWQ/fX1cblxuICAgIFJlYWRNZW1iZXJTb3VyY2VzIC0tPiBBbGxNZW1iZXJTb3VyY2VzUmVhZHt7QWxsIG1lbWJlciBzb3VyY2VzIHJlYWQgd2l0aCBzdWNjZXNzP319XG5cbiAgICBBbGxNZW1iZXJTb3VyY2VzUmVhZCAtLSBObyAtLT4gTGlzdFJlY2VudFVzZXJzKExpc3QgcmVjZW50IHVzZXJzKSAtLT4gU3RvcFxuICAgIEFsbE1lbWJlclNvdXJjZXNSZWFkIC0tIFllcyAtLT4gRXh0ZXJuYWxTb3VyY2VDb25maWd1cmVkXG4gICAgRXh0ZXJuYWxTb3VyY2VDb25maWd1cmVkIC0tIFllcyAtLT4gUmVhZEV4dGVybmFsU291cmNlcyhSZWFkIGFsbCBzb3VyY2VzIGZvciBleHRlcm5hbHMpXG4gICAgRXh0ZXJuYWxTb3VyY2VDb25maWd1cmVkIC0tIE5vICAtLT4gTWVyZ2UoTUVSR0UgbWVtYmVyICYgZXh0ZXJuYWwgZGVsdGFzKVxuXG4gICAgUmVhZEV4dGVybmFsU291cmNlcyAtLT4gQWxsRXh0ZXJuYWxTb3VyY2VzUmVhZHt7QWxsIHNvdXJjZXMgZm9yIGV4dGVybmFscyByZWFkIHdpdGggc3VjY2Vzcz99fVxuXG4gICAgQWxsRXh0ZXJuYWxTb3VyY2VzUmVhZCAtLSBObyAtLT4gTGlzdFJlY2VudFVzZXJzXG4gICAgQWxsRXh0ZXJuYWxTb3VyY2VzUmVhZCAtLSBZZXMgLS0+IE1ha2VNZW1iZXJzRGVsdGEoQ29tcHV0ZSBtZW1iZXJzIGRlbHRhKVxuXG4gICAgTWFrZU1lbWJlcnNEZWx0YSAtLT4gTWFrZUV4dGVybmFsc0RlbHRhKENvbXB1dGUgZXh0ZXJuYWxzIGRlbHRhKVxuICAgIE1ha2VFeHRlcm5hbHNEZWx0YSAtLT4gTWVyZ2VcbiAgICBNZXJnZSAtLT4gSW50ZXJzZWN0aW9uRm91bmR7e0ludGVyc2VjdGlvbiBmb3VuZCBiZXR3ZWVuIG1lbWJlcnMgJiBleHRlcm5hbHM/fX1cblxuICAgIEludGVyc2VjdGlvbkZvdW5kIC0tIFllcyAtLT4gV2FybldpdGhBbWJpZ3VvdXNMb2dpbnMoV2FybiB3aXRoIGFtYmlndW91cyBsb2dpbnNcXG4gJiB1c2UgdGhlbSBhcyBleHRlcm5hbHMpXG4gICAgV2FybldpdGhBbWJpZ3VvdXNMb2dpbnMgLS0+IEFueXRoaW5nVG9DaGFuZ2V7e0FueXRoaW5nIHRvIGNoYW5nZT99fVxuICAgIEludGVyc2VjdGlvbkZvdW5kIC0tIE5vIC0tPiBBbnl0aGluZ1RvQ2hhbmdlXG5cbiAgICBBbnl0aGluZ1RvQ2hhbmdlIC0tIFllcyAtLT4gTWFrZVBheWxvYWQoTWFrZSBDU1YgcGF5bG9hZCB3aXRoIGRlbGV0aW9ucyBmaXJzdClcbiAgICBBbnl0aGluZ1RvQ2hhbmdlIC0tIE5vICAtLT4gRW5kV2l0aFN1Y2Nlc3NcblxuICAgIE1ha2VQYXlsb2FkIC0tPiBTZW5kUGF5bG9hZChTZW5kIHBheWxvYWQgdG8gdGFyZ2V0IHRlbmFudClcblxuICAgIFNlbmRQYXlsb2FkIC0tPiBBbnlFcnJvckRldGVjdGVkMXt7QW55IGJsb2NraW5nIGVycm9yIGRldGVjdGVkP319XG4gICAgQW55RXJyb3JEZXRlY3RlZDEgLS0gWWVzIC0tPiBMaXN0UmVjZW50VXNlcnNcbiAgICBBbnlFcnJvckRldGVjdGVkMSAtLSBObyAgLS0+IFBhdXNlKFdhaXQgc2V2ZXJhbCBtaW51dGVzIGZvciBjaGFuZ2VzIHRvIGJlIGFwcGxpZWQpXG5cbiAgICBQYXVzZSAtLT4gQ2hlY2tSZXN1bHQoQ2hlY2sgaW1wb3J0IHJlc3VsdCkgLS0+IEFueUVycm9yRGV0ZWN0ZWQye3tBbnkgYmxvY2tpbmcgZXJyb3IgZGV0ZWN0ZWQ/fX1cbiAgICBBbnlFcnJvckRldGVjdGVkMiAtLSBZZXMgLS0+IExpc3RSZWNlbnRVc2Vyc1xuICAgIEFueUVycm9yRGV0ZWN0ZWQyIC0tIE5vIC0tPiBBbnlTdWNjZXNze3tBbnkgc3VjY2Vzcz99fVxuICAgIEFueVN1Y2Nlc3MgLS0gTm8gLS0+IFN0b3BcbiAgICBBbnlTdWNjZXNzIC0tIFllcyAtLT4gRW5kV2l0aFN1Y2Nlc3MoRW5kIHdpdGggc3VjY2VzcylcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19

Here is the input markdown (I only removed mermaid from the first line):
```
  flowchart TD
    ReadScriptParameters(Read script parameters) -->
    ChoosePodAndTenant(Choose POD and tenant\n Default values are in config) -->
    PodAndTenantFound{{POD and tenant found?}}
    PodAndTenantFound -- No --> Stop(STOP synchro\n with failure status)
    PodAndTenantFound -- Yes --> UserSourceConfigured{{Any user source configured?}}

    UserSourceConfigured -- No --> Stop
    UserSourceConfigured -- Yes --> MemberSourceConfigured{{Any member source configured?}}
    MemberSourceConfigured -- Yes --> ReadMemberSources(Read all member sources)
    MemberSourceConfigured -- No  --> ExternalSourceConfigured{{Any external source configured?}}

    ReadMemberSources --> AllMemberSourcesRead{{All member sources read with success?}}

    AllMemberSourcesRead -- No --> ListRecentUsers(List recent users) --> Stop
    AllMemberSourcesRead -- Yes --> ExternalSourceConfigured
    ExternalSourceConfigured -- Yes --> ReadExternalSources(Read all sources for externals)
    ExternalSourceConfigured -- No  --> Merge(MERGE member & external deltas)

    ReadExternalSources --> AllExternalSourcesRead{{All sources for externals read with success?}}

    AllExternalSourcesRead -- No --> ListRecentUsers
    AllExternalSourcesRead -- Yes --> MakeMembersDelta(Compute members delta)

    MakeMembersDelta --> MakeExternalsDelta(Compute externals delta)
    MakeExternalsDelta --> Merge
    Merge --> IntersectionFound{{Intersection found between members & externals?}}

    IntersectionFound -- Yes --> WarnWithAmbiguousLogins(Warn with ambiguous logins\n & use them as externals)
    WarnWithAmbiguousLogins --> AnythingToChange{{Anything to change?}}
    IntersectionFound -- No --> AnythingToChange

    AnythingToChange -- Yes --> MakePayload(Make CSV payload with deletions first)
    AnythingToChange -- No  --> EndWithSuccess

    MakePayload --> SendPayload(Send payload to target tenant)

    SendPayload --> AnyErrorDetected1{{Any blocking error detected?}}
    AnyErrorDetected1 -- Yes --> ListRecentUsers
    AnyErrorDetected1 -- No  --> Pause(Wait several minutes for changes to be applied)

    Pause --> CheckResult(Check import result) --> AnyErrorDetected2{{Any blocking error detected?}}
    AnyErrorDetected2 -- Yes --> ListRecentUsers
    AnyErrorDetected2 -- No --> AnySuccess{{Any success?}}
    AnySuccess -- No --> Stop
    AnySuccess -- Yes --> EndWithSuccess(End with success)
```

**Comment by jihchi** [comment]
![carbon](https://user-images.githubusercontent.com/87983/224267680-b3bd313d-4895-45aa-8839-60f9a1d6f6b7.png)

Because there was a few slashes in the link (after `https://mermaid.ink/img/`), that is unexpected.

How did you get the link?

This [link](https://mermaid.ink/img/pako:eNqdVsGO2jAQ_RUrh1WQdg_dI4dWCGhVabeLgHZViYuJB2KR2JHt7BYh_r1jOw5JSFi1nMwbz_PMvPE4pyiRDKJxRMguk-9JSpUh69lGEPwtgbJVonhhFlTRHAwoHVuQaIeSooZH5OHhs_eaplJqWEg2EWwNggoTe4gsXmaECkaMQze4fQY7WmaGvNGsBE2oAsIFSaTY8X2Dskn2VZaCnU5tLrKz6JfzeWA_UpEf0hKSlZFFvFq_LIg-iiRV0sbxzk1KdpRnJUagDTWlHt2g-o2xWq6fGtRKliqBqQsZvTG0iTiSEi1EO1OVjrW5AD1vn2snytsbQwzPkG-HosidbSAOS97v3KS3cjd3VQ1As6zNHuo1zIiZOcb5H2wYQbP-kKGy3izeVVCOeJJlLdDuQtKrSImyGTjJdZkgoBvUfSQNXZ64NktIQBiri47tf-SzgNPcX4SGfEN8ob5D1fDeQ9auQu19DY1Cyjup6tIGqW6RB7GeQe0hfp4vv81DFe8uGjHIDLV0F1k6kQRhOvBFmt4AP1Koh21Yo4-86otED-Cl0jObVzyVeVEaqPLWPts62e72miMc02G5JBd4Akvb4VL2cKFw6cDvwk5aSAyXopqCTcjPQLIF8w4g6qgvcjWLeMXVrMQrVeIViz_Jt9gRstRPcs-Fji3uVaHBQjJnsjP0zl4AYlLICdVXzTbA6ftDHE3KxX4tpykVe3CTwCHESJI4rB5ZvZFXyneJ6pbp4F3ZF_SYScpiuybT1S982Bzgk0W9wJ6GTcqVNqNhznrECWZzXfnebXZMdZIfEiBYONmu61MxaUNRdVO9bnXPNTxCvnOlpJrhG5wYYJ_8DN1mMjnY6oE1YvzeWpfwyq1Zj_7b0-cRsl1QFB6bgxui4Q0UDoacC-x5f6u9ftpmtQVCiyLjwOqUnLOjmaaQHJag8XsgdmvC80IqO14tNurN-PH_Mn7854wf221WSetPb86oyrey977obXP9ELR6Jsa_rQE4iu6jHFROOcOvtZNl2kT2ssEmGuOSUXXYRBtxxn20NHKFHzfR2KgS7qOyYNTAjNM9fq5F4x3eyhqdM26k8jvPfwF7YX2G?type=png) works:

<details>  
<summary>Image (click to expand)</summary>

[![](https://mermaid.ink/img/pako:eNqdVlFv2jAQ_iunPFRBah_Wxz5sQsCmSe2KgK2axIuJD2KR2Mh22iHU_76znYQkJFQbT-Y73-e7-87nnKJEcYweIoBtpt6SlGkLq-laAv0WyPgy0eJg50yzHC1qEzsQjEfhUMMjuLv7HLwmqVIG54qPJV-hZNLGAYL58xSY5GA9uqbtU9yyIrPwyrICDTCNICQkSm7FrkHZJPuqCslPpzYXbB365f19YD9RwQ_lCGFp1SFerp7nYI4ySbVycbwJm8KWiaygCIxltjCjK1S_KVbH9dOgXqpCJzjxIZM3hTaWRyjIAsabynSczQcYePtcO1Fe31jF8IT5ZiiK3NsG4nDk_c5Neid3c1fZACzL2uxVvYYZKTPPOPtDDSNZ1h8yltarxbsIyhOPs6wFul1EehEpaJeBl9wUCQGmQd1H0tDlURi7wASldbqY2P0nPgd4zcNFaMg3xFfVd6gawXvI2lWova-hUZXyVum6tJVU18grsZ5Q7zB-mi2-zaoq3pw14phZ5ujOsnQiqYTpwGdpegP8SKEetmGNPvKqLxLbY5DKTF1e8UTlh8JimbcJ2dbJdrfXHNUxHZZzchVPxdJ2OJe9ulC09OB36SYtJlYoWU7BJhRmIGzQviHKOuqzXM0iXnA1K_HCtHyh4o_zDXWEKsyj2glpYocHVVhlgcyb3Ay9cRcAbIo5MHPRbAOcoT_k0aZC7lZqkjK5Qz8JPAJWQeKxemT1Rl4q3yWqW6aDd2Wfs2OmGI_dGibLX_SweSAkS3qhO42aVGhjR8Oc9YiT3OW6DL3b7JjypDAkUPLqZLeuT6WkLSPVbfm61T3X8KjynWmt9JTe4MQi_xRm6CZTyd5VD52R4g_WuoQXbs169N-ePo8q2zkj4ak5hAWDr6hpMORCUs-HWx30My6rDQI7HDKBvE7JO3uaSYrJfoGGvgdivwaRH5R249Vho96M7_8v4_t_zvi-3WaltOH05owqfUt774veNtcPQatnYvrbGoCj6DbKUedMcPpaOzmmdeQuG66jB1pypvfraC3faR8rrFrSx030YHWBt1Fx4MziVLAdfa61wRkXVumAvf8F_-V9Ow?type=png)](https://mermaid.live/edit#pako:eNqdVlFv2jAQ_iunPFRBah_Wxz5sQsCmSe2KgK2axIuJD2KR2Mh22iHU_76znYQkJFQbT-Y73-e7-87nnKJEcYweIoBtpt6SlGkLq-laAv0WyPgy0eJg50yzHC1qEzsQjEfhUMMjuLv7HLwmqVIG54qPJV-hZNLGAYL58xSY5GA9uqbtU9yyIrPwyrICDTCNICQkSm7FrkHZJPuqCslPpzYXbB365f19YD9RwQ_lCGFp1SFerp7nYI4ySbVycbwJm8KWiaygCIxltjCjK1S_KVbH9dOgXqpCJzjxIZM3hTaWRyjIAsabynSczQcYePtcO1Fe31jF8IT5ZiiK3NsG4nDk_c5Neid3c1fZACzL2uxVvYYZKTPPOPtDDSNZ1h8yltarxbsIyhOPs6wFul1EehEpaJeBl9wUCQGmQd1H0tDlURi7wASldbqY2P0nPgd4zcNFaMg3xFfVd6gawXvI2lWova-hUZXyVum6tJVU18grsZ5Q7zB-mi2-zaoq3pw14phZ5ujOsnQiqYTpwGdpegP8SKEetmGNPvKqLxLbY5DKTF1e8UTlh8JimbcJ2dbJdrfXHNUxHZZzchVPxdJ2OJe9ulC09OB36SYtJlYoWU7BJhRmIGzQviHKOuqzXM0iXnA1K_HCtHyh4o_zDXWEKsyj2glpYocHVVhlgcyb3Ay9cRcAbIo5MHPRbAOcoT_k0aZC7lZqkjK5Qz8JPAJWQeKxemT1Rl4q3yWqW6aDd2Wfs2OmGI_dGibLX_SweSAkS3qhO42aVGhjR8Oc9YiT3OW6DL3b7JjypDAkUPLqZLeuT6WkLSPVbfm61T3X8KjynWmt9JTe4MQi_xRm6CZTyd5VD52R4g_WuoQXbs169N-ePo8q2zkj4ak5hAWDr6hpMORCUs-HWx30My6rDQI7HDKBvE7JO3uaSYrJfoGGvgdivwaRH5R249Vho96M7_8v4_t_zvi-3WaltOH05owqfUt774veNtcPQatnYvrbGoCj6DbKUedMcPpaOzmmdeQuG66jB1pypvfraC3faR8rrFrSx030YHWBt1Fx4MziVLAdfa61wRkXVumAvf8F_-V9Ow)
</details>

Here is how I generate the link:
1. Go to https://mermaid.live/
2. Copy & paste the input into `</> Code` on the editor
3. Expand `Actions` 
4. Click `Copy markdown`

**Comment by PixEye** [comment]
Thank you @jihchi for your reply.
I found the link inside an error message of a tool used to transfer .md files to a web site.
It is an automatic process and I would rather prefer to avoid a copy/paste each time I have to use it... 😕

Is it possible to fix the https://mermaid.ink/img/ API and support slashes in the data?

Or does the tool I use has to adapt and for example automatically remove the slashes?

**Comment by jihchi** [comment]
May I know which tool you used to generate mermaid.ink URL?

It seems like a bug in the tool because the encoded code should not contain slashes.

**Comment by PixEye** [comment]
Thanks again for your reply. My mate fixed his tool.
Best regards.
