### ISSUE TITLE
No picture in the docs

### ISSUE THREAD

**Issue by OnkelTem** [jihchi/mermaid.ink#72]
Hi!

I was reading this page https://mswjs.io/docs/#request-flow-diagram and stumbled upon a picture which doesn't show up:

![image](https://user-images.githubusercontent.com/114060/172386666-69066f66-e2f0-403a-a7d4-34ecc6c6d023.png)

If I try to open the picture directry in the browser I get an error:

![image](https://user-images.githubusercontent.com/114060/172386858-824bc7fd-a90a-440c-99c1-2274d404c714.png)

Any ideas?

**Comment by tristanmarsh** [comment]
Appears to be working for me now, but it does raise the question how reliable is this host vs the (official?) [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor). I'm assuming it's reliable because it's linked by the editor?

Are there any docs or commitments to the support of the project? 😄 

![Screen Shot 2022-06-08 at 1 28 55 pm](https://user-images.githubusercontent.com/3328024/172526166-739ed1dc-96ed-47d4-b329-0ab95a2ddb28.png)
